-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;
-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- ENUM types
CREATE TYPE document_type_enum AS ENUM ('rfp', 'case study');



-- User
CREATE TABLE  "user" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(100),
    name VARCHAR(100) NOT NULL,
    password_at TIMESTAMP,
    login_at TIMESTAMP,
    status SMALLINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    signup_type INT DEFAULT 1,  -- SignupType enum
    role INT DEFAULT 1          -- UserRole enum
);

-- User Profile
CREATE TABLE  user_profile (
    user_id INT PRIMARY KEY REFERENCES "user"(id) ON DELETE CASCADE,
    tone_score JSONB,           -- "formal", "casual"
    verbosity_score JSONB,      -- "summary", "detailed"
    technology_interest JSONB,
    domain_interest JSONB,      -- [{"tag": "python", "score": 0.8}]
    recent_query JSONB
);

-- Session
CREATE TABLE  session (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES "user"(id) ON DELETE CASCADE,
    is_active SMALLINT DEFAULT 0, 
    name VARCHAR(255) NOT NULL ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Message
CREATE TABLE  message (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INT REFERENCES session(id) ON DELETE CASCADE,
    message VARCHAR(10240),
    direction SMALLINT,     -- 1=user, 2=bot
    has_file SMALLINT,      -- 0=true, 1=false
    file_name VARCHAR(255),
    file_path VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- File Import
CREATE TABLE  file_import (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES "user"(id) ON DELETE SET NULL,
    name VARCHAR(255) NOT NULL,
    path VARCHAR(500) NOT NULL,
    size BIGINT DEFAULT 0,
    type INT DEFAULT 0,          -- FileType enum
    domain VARCHAR(100),
    client_name VARCHAR(100),
    status SMALLINT DEFAULT 0,        -- Status enum
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Batch
CREATE TABLE  batch (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES "user"(id) ON DELETE SET NULL,
    file_id INT REFERENCES file_import(id) ON DELETE CASCADE,
    host VARCHAR,
    status SMALLINT DEFAULT 0,        -- Status enum
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Clients
CREATE TABLE  client (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100)
);

-- Project
CREATE TABLE  project (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INT REFERENCES client(id) ON DELETE SET NULL,
    name VARCHAR(100),
    description VARCHAR(4096)
);

-- Domain
CREATE TABLE  domain (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE
);

-- Technology
CREATE TABLE  technology (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE
);

-- Project-Technology
CREATE TABLE  project_technology (
    project_id INT REFERENCES project(id) ON DELETE CASCADE,
    technology_id INT REFERENCES technology(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, technology_id)
);

-- Project-Domain
CREATE TABLE  project_domain (
    project_id INT REFERENCES project(id) ON DELETE CASCADE,
    domain_id INT REFERENCES domain(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, domain_id)
);

-- Document
CREATE TABLE  document (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INT REFERENCES project(id) ON DELETE CASCADE,
    content VARCHAR(8000),
    name VARCHAR(50),
    type document_type_enum,
    file_path VARCHAR(500)
);

-- LangChain Collection
CREATE TABLE  langchain_pg_collection (
    uuid UUID PRIMARY KEY,
    name VARCHAR,
    cmetadata JSONB
);

INSERT INTO langchain_pg_collection (uuid, name, cmetadata)
VALUES
    (gen_random_uuid(), 'Slide_Embeddings', '{"description": "Slide embeddings for projects"}'::jsonb),
    (gen_random_uuid(), 'recall_memories', '{"description": "User session memories for semantic recall"}'::jsonb)
ON CONFLICT DO NOTHING;

-- LangChain Embedding
CREATE TABLE  langchain_pg_embedding (
    id VARCHAR NOT NULL PRIMARY KEY,
    collection_id UUID NOT NULL REFERENCES langchain_pg_collection(uuid) ON DELETE CASCADE,
    embedding VECTOR(3072),
    document VARCHAR,
    cmetadata JSONB
);

-- File Technology
CREATE TABLE file_technology (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,       -- auto-incrementing primary key
    file_id integer NOT NULL REFERENCES public.file_import(id)     -- foreign key
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    technology_name varchar(50) NOT NULL,                          -- technology name
    CONSTRAINT unique_file_technology UNIQUE (file_id, technology_name)  -- unique constraint
);



